ARM64: Add suppoort for arm64 architecture
Added Support for arm64 architecture so that yardstick framework
can be ran on arm-pod1 the armband CI pod. The modifications include
Testing for arm64 architecture an running arm64 specific code.
The Openstack doesn't boot 3.13 kernel so it was modified with 3.19
kernel available in vivid cloud image of ubuntu jira case ARMBAND-40.

Change-Id: I906d4adbcf2ec2c0f1d695d9916ede42f4151080
Signed-off-by: Paul Vaduva <Paul.Vaduva@enea.com>

diff --git a/tests/ci/yardstick-verify b/tests/ci/yardstick-verify
--- a/tests/ci/yardstick-verify
+++ b/tests/ci/yardstick-verify
@@ -44,6 +44,8 @@ DISPATCHER_TYPE=file
 DISPATCHER_FILE_NAME="/tmp/yardstick.out"
 DISPATCHER_HTTP_TARGET="http://testresults.opnfv.org/test/api/v1/results"
 DISPATCHER_INFLUXDB_TARGET=
+HOST="cloud-images.ubuntu.com"
+ARM64_KERNEL_VERSION="vivid"
 
 while getopts "r:i:h" OPTION; do
     case $OPTION in
@@ -80,7 +82,7 @@ cleanup()
         return
     fi
 
-    for image in $(glance image-list | grep -e cirros-0.3.3 -e yardstick-trusty-server -e Ubuntu-14.04 | awk '{print $2}'); do
+    for image in $(glance image-list | grep -e cirros-0.3.3 -e yardstick-trusty-server -e Ubuntu-14.04 -e yardstick-vivid-kernel | awk '{print $2}'); do
         echo "Deleting image $image..."
         glance image-delete $image || true
     done
@@ -233,11 +235,47 @@ load_yardstick_image()
     echo
     echo "========== Loading yardstick cloud image =========="
 
-    output=$(glance --os-image-api-version 1 image-create \
-        --name yardstick-trusty-server \
-        --is-public true --disk-format qcow2 \
-        --container-format bare \
-        --file $QCOW_IMAGE)
+    if [ $YARD_IMG_ARCH = "arm64" ]; then
+	cd /tmp
+	if [ ! -f /tmp/vivid-server-cloudimg-arm64.tar.gz ]; then
+		wget $HOST/$ARM64_KERNEL_VERSION/current/vivid-server-cloudimg-arm64.tar.gz
+	fi
+	if [ ! -f /tmp/vivid-server-cloudimg-arm64-vmlinuz-generic ]; then
+		tar zxf vivid-server-cloudimg-arm64.tar.gz vivid-server-cloudimg-arm64-vmlinuz-generic
+	fi
+	VIVID_IMAGE="/tmp/vivid-server-cloudimg-arm64.tar.gz"
+	KERNEL_IMAGE="/tmp/vivid-server-cloudimg-arm64-vmlinuz-generic"
+	create_vivid_kernel=$(glance --os-image-api-version 1 image-create \
+			--name yardstick-vivid-kernel \
+			--is-public true --disk-format qcow2 \
+			--container-format bare \
+			--file $KERNEL_IMAGE)
+
+	GLANCE_KERNEL_ID=$(echo "$create_vivid_kernel" | grep " id " | awk '{print $(NF-1)}')
+	if [ -z "$GLANCE_KERNEL_ID" ]; then
+		echo 'Failed uploading kernel to cloud'.
+		exit 1
+	fi
+
+
+	output=$(glance --os-image-api-version 1 image-create \
+		--name yardstick-trusty-server \
+		--is-public true --disk-format qcow2 \
+		--container-format bare \
+		--property kernel_id=$GLANCE_KERNEL_ID \
+		--property os_command_line="root=/dev/vdb1 console=tty0 console=ttyS0 console=ttyAMA0 rw" \
+		--file $QCOW_IMAGE)
+	sudo rm -f $KERNEL_IMAGE
+	sudo rm -f $VIVID_IMAGE
+        cd $YARDSTICK_REPO_DIR
+    else
+	output=$(glance --os-image-api-version 1 image-create \
+		--name yardstick-trusty-server \
+		--is-public true --disk-format qcow2 \
+		--container-format bare \
+		--file $QCOW_IMAGE)
+    fi
+
     echo "$output"
 
     GLANCE_IMAGE_ID=$(echo "$output" | grep " id " | awk '{print $(NF-1)}')
@@ -429,10 +467,14 @@ main()
 
     build_yardstick_image
     load_yardstick_image
-    load_cirros_image
-    load_ubuntu_image
+    if [ $YARD_IMG_ARCH != "arm64" ]; then
+	load_cirros_image
+	load_ubuntu_image
+    else
+	sed -i 's/image: cirros-0.3.3/image: TestVM/g' tests/opnfv/test_cases/opnfv_yardstick_tc002.yaml
+	sed -i 's/image: cirros-0.3.3/image: TestVM/g' samples/ping.yaml
+    fi
     create_nova_flavor
-
     install_storperf
     run_test
     remove_storperf
