ci: Freeze pip requirements + cleanups
Freeze pip requirements for brahmaputra release to make sure we
keep track of dependencies.

Fixes internalURL problem with ericsson-virtual1

Add check to verify that nova, glance and heat services are functional

Change-Id: I15c3d215596eaad31f8e260d129b8e07a7d63976
Signed-off-by: Jo¶rgen Karlsson <jorgen.w.karlsson@ericsson.com>

diff --git a/ci/yardstick-verify b/ci/yardstick-verify
--- a/ci/yardstick-verify
+++ b/ci/yardstick-verify
@@ -112,10 +112,11 @@ install_yardstick()
     echo
     echo "========== Installing yardstick =========="
 
-    if ! sudo python setup.py install; then
-        echo 'Yardstick installation failed!'
-        exit 1
-    fi
+    # uninstall previous version
+    pip uninstall -y yardstick || true
+
+    # Install yardstick
+    pip install .
 }
 
 build_yardstick_image()
@@ -315,9 +316,7 @@ main()
     for suite in ${SUITE_FILES[*]}; do
         echo "     $suite"
     done
-
-    # install yardstick
-    install_yardstick
+    echo
 
     # check if some necessary variables is set
     if [ -z "$OS_AUTH_URL" ]; then
@@ -325,12 +324,21 @@ main()
         exit 1
     fi
 
-    # check if the api is up
-    echo "Checking if OS API is working..."
-    if ! glance image-list > /dev/null; then
-        echo "OS API is down"
-        exit 1
-    fi
+    echo "OS_AUTH_URL is $OS_AUTH_URL"
+    echo
+
+    # check OpenStack services
+    echo "Checking OpenStack services:"
+    for cmd in "glance image-list" "nova list" "heat stack-list"; do
+        echo "  checking ${cmd/%\ */} ..."
+        if ! $cmd >/dev/null; then
+            echo "error: command \"$cmd\" failed"
+            exit 1
+        fi
+    done
+
+    # install yardstick
+    install_yardstick
 
     cleanup
 
