restore the yardstick-img-modify cleanup() func
There is a result failed again after last update.
So i restore the clean() function to its original codes and avoid CI failed.
But i'm not sure something about the clean() function,
and I will check this failed clearly in future.

Change-Id: I8f49533788c7ccb2016e7a484368a72028579fa8
JIRA: YARDSTICK-502
Signed-off-by: Ryan.RCS <lihainong@huawei.com>

diff --git a/tools/yardstick-img-modify b/tools/yardstick-img-modify
--- a/tools/yardstick-img-modify
+++ b/tools/yardstick-img-modify
@@ -154,9 +154,11 @@ cleanup() {
     mount | grep "/mnt/vivid" && umount "/mnt/vivid"
 
     if [ -f $raw_imgfile ]; then
-        if [ -z "$(kpartx -l $raw_imgfile | grep 'loop deleted')" ]; then
-            kpartx -dv $raw_imgfile
-        fi
+        #TBD: kpartx -dv $raw_imgfile sometimes failed, we should checked it agein.  
+        #if [ -z "$(kpartx -l $raw_imgfile | grep 'loop deleted')" ]; then
+        #    kpartx -dv $raw_imgfile
+        #fi
+        kpartx -dv $raw_imgfile || true
     fi
 
     rm -f $raw_imgfile
