Add cleanup trap to yardstick-img-modify
Fixes a problem with loopback devices not
beeing detached when the image build fails.

Change-Id: I3e422be4fb0157289a032c14700e184f58d544d9
Signed-off-by: Jo¶rgen Karlsson <jorgen.w.karlsson@ericsson.com>

diff --git a/tools/yardstick-img-modify b/tools/yardstick-img-modify
--- a/tools/yardstick-img-modify
+++ b/tools/yardstick-img-modify
@@ -25,6 +25,7 @@
 #
 
 set -e
+set -x
 
 die() {
     echo "error: $1" >&2
@@ -117,13 +118,34 @@ cleanup() {
     rm -rf $mountdir
 }
 
-set -x
+exitcode=""
+error_trap()
+{
+    local rc=$?
+
+    set +e
+
+    if [ -z "$exitcode" ]; then
+        exitcode=$rc
+    fi
+
+    cleanup
+
+    echo "Image build failed with $exitcode"
+
+    exit $exitcode
+}
 
 main() {
     cleanup
+
+    trap "error_trap" EXIT SIGTERM
+
     download
     setup
     modify
+
+    trap - EXIT SIGTERM
     cleanup
 
     echo "the modified image is found here: $imgfile"
